import { Inter } from 'next/font/google'
import './globals.css'
import Home from './page'
import Navbar from './Navbar/page'
import Bottom from './Navbar/bottom'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Bottom />
      </body>
      
    </html>
  )
}
